server:
  port: 8888
  servlet:
    context-path: /demo
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://john.db.elephantsql.com:5432/purnjyir
    username: 	purnjyir
    password: HmtpVdJDBB2jv3h2kgtL5JXsBKKMlBt4
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher